### ISSUE TITLE
Any environment installation tips?

### ISSUE THREAD

**Issue by MarcuXu** [ZidongLiu/DeComFL#15]
Hi Liu, I think your work is excellent! However, I am unable to find any instructions on how to set up your environment and replicate your experiments. Could you please share your experiment setup on Github? Thank you so much!

**Comment by RogerRogerUSC** [comment]
Hi Xu, thank you for your comments. We put all the needed packages in the requirements.txt file, but it is just for training tasks. Next, we will add more packages for LLM fine-tuning tasks after we finish codes related to LLMs.

**Comment by ZidongLiu** [comment]
hi @MarcuXu, 

Here is a quick tutorial for conda.

1. you could start a new conda env with python >= 3.10. Follow instruction here. https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands

2. Then inside the conda env, cd to root folder, do `pip install -r requirements.txt`. The requirements.txt is up to date now.

3. Inside conda env, try to run `python cezo_fl.py dataset=sst2` to test if llm can be fine tuned for 'SST2' task.

**Comment by ZidongLiu** [comment]
Please refer to https://github.com/ZidongLiu/DeComFL?tab=readme-ov-file#environment-setup for more details
